apiVersion: v1
kind: Service
metadata:
        #  annotations:
        #cloud.google.com/load-balancer-type: "Internal"
  name: http-v1
  namespace: default
  labels:
     service: http
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: http
#    version: v1
