apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-kila-hl
  labels:
     service: nginx-kila
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: nginx-kila
