apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-hl
  namespace: kila
  labels:
     service: nginx
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: nginx
