apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
  namespace: kila
  labels:
     service: nginx
spec:
  type: LoadBalancer
#  loadBalancerSourceRanges:
#    - "116.241.212.54/32"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: nginx
