apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: kila
  labels:
    service: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: nginx
