apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        name: nginx
        version: v1
    spec:
      #nodeSelector:
      #  node: wallet
      volumes:
        - name: web-index
          configMap:
            name: index
      containers:
      - name: nginx
        image: nginx:1.11.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
         requests:
            cpu: 50m
            memory: 100m
        volumeMounts:
          - name: web-index
            readOnly: true
            mountPath: /usr/share/nginx/html 
