apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kila
  namespace: kila
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx-kila
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nginx-kila
        version: v1
    spec:
      #nodeSelector:
      #  node: wallet
      volumes:
        - name: web-index
          configMap:
            name: index-kila
      containers:
      - name: nginx
        image: nginx:1.11.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
         requests:
            cpu: 50m
            memory: 100m
        volumeMounts:
          - name: web-index
            readOnly: true
            mountPath: /usr/share/nginx/html 
