apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kila
  namespace: kila
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: web
        - containerPort: 443
          name: ssl
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
