apiVersion: v1
appVersion: 2.3.0
deprecated: true
description: DEPRECATED - nfs-server-provisioner is an out-of-tree dynamic provisioner
  for Kubernetes. You can use it to quickly & easily deploy shared storage that works
  almost anywhere.
home: https://github.com/kubernetes/charts/tree/master/stable/nfs-server-provisioner
keywords:
- nfs
- storage
name: nfs-server-provisioner
sources:
- https://github.com/kubernetes-incubator/external-storage/tree/master/nfs
version: 1.1.3
