apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: default
  labels:
     name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx
