apiVersion: v1
kind: Service
metadata:
  name: http-service
  namespace: default
  labels:
     service: http-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: http-server
