apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: kila
spec:
  rules:
  - http:
      paths:
      - path: /v1
        backend:
          serviceName: nginx-svc-v1
          servicePort: 80
      - path: /v2
        backend:
          serviceName: nginx-svc-v2
          servicePort: 80
