apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
  namespace: kila
spec:
  serviceName: mysql-sts-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql-sts
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      #storageClassName: faster
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        app: mysql-sts
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
