apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
  namespace: kila
spec:
  serviceName: nginx-sts-svc
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sts
  volumeClaimTemplates:
  - metadata:
      name: nginx-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: nginx-data
              mountPath: /data
