apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: kila
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nginx
    spec:
      volumes:
        - name: ca
          secret:
            secretName: ca-secret
      containers:
      - name: nginx
        image: nginx:1.11.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
         requests:
            cpu: 50m
            memory: 100m
        envFrom:
          - secretRef:
              name: env-secret
        volumeMounts:
          - name: ca
            readOnly: true
            mountPath: /usr/share/nginx/html/key/
