apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: kila
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nginx
    spec:
      volumes:
        - name: index-v1
          configMap:
            name: index-v1
        - name: web-html
          configMap:
            name: web-html
        - name: config-default
          configMap:
            name: config-default
      containers:
      - name: nginx
        image: nginx:1.11.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
         requests:
            cpu: 50m
            memory: 100m
         limits:
            cpu: 100m
            memory: 256Mi
        envFrom:
          - configMapRef:
              name: env
        volumeMounts:
          - name: index-v1
            readOnly: true
            mountPath: /usr/share/nginx/html
            #subPath: index.html 
          - name: web-html
            readOnly: true
            mountPath: /usr/share/nginx/html/kila/
          - name: config-default
            readOnly: true
            mountPath: /etc/nginx/conf.d
        #    subPath: default.conf
