apiVersion: v1
kind: ConfigMap
metadata:
  name: config-default
  namespace: kila
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html/kila/;
            index  index.html index.htm;
        }
    }
