apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: default
  labels:
     app: prometheus
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    name: web
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
