apiVersion: v1
kind: Service
metadata:
  namespace: db 
  name: mysql
spec:
  ports:
    - port: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: db
  name: mysql
subsets:
  - addresses:
      - ip: 10.20.51.211
    ports:
      - port: 3306
