apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
  namespace: web
spec:
  #storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
