apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: web
  labels:
     app: wordpress
spec:
  type: LoadBalancer
#  loadBalancerSourceRanges:
#    - "116.241.212.54/32"
  externalTrafficPolicy: Local
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    app: wordpress
