apiVersion: v1
kind: Service
metadata:
  name: mysql-sts-svc
  namespace: default
  labels:
     app: mysql-sts
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    name: web
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-sts
