---
# Source: redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-one
  namespace: "redis"
  labels:
    app.kubernetes.io/instance: redis-one
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.2
    helm.sh/chart: redis-20.11.3
type: Opaque
data:
  redis-password: "endZbDIwazdUSg=="
