apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
     app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: web
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
