apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dp-tomcat-hpa
  namespace: kila
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-tomcat
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
