apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: kila
  labels:
    app: dp-tomcat
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dp-tomcat
