apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dp-tomcat-hpa
  namespace: kila
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-tomcat
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
