apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: http-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: http-server
        version: v2
    spec:
#      initContainers:
#      - name: increase-fd-ulimit
#        image: busybox
#        command: ["sh", "-c", "ulimit -n 65536"]
#        securityContext:
#          privileged: true
      containers:
      - name: nginx-v2
        image: nginx:1.16.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
         requests:
            cpu: 200m
