apiVersion: v1
kind: Service
metadata:
  name: sqlserver-deployment
spec:
  selector:
    app: ms-sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "111.252.94.175/32"
