apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-volume-0
  namespace: sqlserver
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
