apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: echo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 2
      parallelism: 1
      template:
        spec:
          containers:
          - name: echo
            image: busybox
            command: 
              - date
          restartPolicy: Never
