apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: prometheus-svc
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: prometheus-conf
          configMap:
            name: prometheus-conf
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 600m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 128Mi
          volumeMounts:
            - name: prometheus-conf
              readOnly: true
              mountPath: /etc/prometheus/
            - name: prometheus-data
              mountPath: /prometheus/
