apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kila
  labels:
    name: busybox
spec:
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "36000"
    name: busybox
