apiVersion: v1
kind: Pod
metadata:
  name: nginx-kila
  namespace: kila
  labels:
    service: nginx
spec:
  containers:
   - name: web
     image: nginx:1.11.5
     ports:
     - containerPort: 80
     #env:
     #- name: TZ
     #  value: Asia/Taipei
